package cmd

func init() {
	workitemSearchCmd.Flags().String("category", "Req", "category")
	workitemSearchCmd.Flags().String("space-id", "", "project/space id (default: profile.space_id; required)")
	workitemSearchCmd.Flags().String("assigned-to", "", "assignee user id or 'self'")
	workitemSearchCmd.Flags().String("creator", "", "creator user id or 'self'")
	workitemSearchCmd.Flags().String("subject", "", "subject contains")
	workitemSearchCmd.Flags().String("status", "", "status ids, comma-separated (fieldIdentifier status / className status)")
	workitemSearchCmd.Flags().String("status-stage", "", "status stage ids, comma-separated")
	workitemSearchCmd.Flags().String("type", "", "work item type ids, comma-separated")
	workitemSearchCmd.Flags().String("priority", "", "priority ids, comma-separated")
	workitemSearchCmd.Flags().String("order-by", "gmtCreate", "orderBy")
	workitemSearchCmd.Flags().String("sort", "desc", "asc|desc")
	workitemSearchCmd.Flags().Int("page", 1, "page")
	workitemSearchCmd.Flags().Int("per-page", 20, "per page (OpenAPI max 200)")
	workitemSearchCmd.Flags().Bool("all", false, "follow all pages (ListAll, max 50); dedupe by workitem id")
	workitemSearchCmd.Flags().Bool("as-items", false, "wrap data as {items, pagination} (opt-in stable shape for scripts; default off)")
	const dateHelp = `datetime "YYYY-MM-DD HH:MM:SS" (OpenAPI BETWEEN inclusive; e.g. "2026-09-01 00:00:00"; client-filter if server returns extras)`
	workitemSearchCmd.Flags().String("created-after", "", "filter gmtCreate >= value; "+dateHelp)
	workitemSearchCmd.Flags().String("created-before", "", "filter gmtCreate <= value; "+dateHelp)
	workitemSearchCmd.Flags().String("updated-after", "", "filter gmtModified >= value; "+dateHelp)
	workitemSearchCmd.Flags().String("updated-before", "", "filter gmtModified <= value; "+dateHelp)
	workitemSearchCmd.Flags().String("finish-after", "", "filter finishTime >= value; "+dateHelp)
	workitemSearchCmd.Flags().String("finish-before", "", "filter finishTime <= value; "+dateHelp)
	workitemGetCmd.Flags().String("id", "", "work item id or serial (or positional arg)")
	workitemGetCmd.Flags().Bool("full", false, "print the raw work item (pre-0.16.34 output; default: brief view)")
	workitemGetCmd.Flags().Bool("brief", false, "brief view (default): key fields + description_summary; env YUNXIAO_WORKITEM_GET_VIEW=full|brief applies when no view flag")
	workitemGetCmd.Flags().String("fields", "", "comma-separated top-level keys to keep, e.g. subject,description (raw values)")
	workitemCommentsListCmd.Flags().String("id", "", "work item id (required)")
	workitemCommentsListCmd.Flags().Int("page", 1, "page")
	workitemCommentsListCmd.Flags().Int("per-page", 20, "per page")
	addSortFlag(workitemCommentsListCmd)
	workitemCommentsDeleteCmd.Flags().String("id", "", "work item id or serial (required)")
	workitemCommentsDeleteCmd.Flags().String("comment-id", "", "comment id (required)")
	workitemCommentsUpdateCmd.Flags().String("id", "", "work item id or serial (required)")
	workitemCommentsUpdateCmd.Flags().String("comment-id", "", "comment id (required)")
	workitemCommentsUpdateCmd.Flags().String("content", "", "new comment content (or use --content-file)")
	workitemCommentsUpdateCmd.Flags().String("content-file", "", "UTF-8 file for new comment body (BOM stripped)")
	workitemCommentsUpdateCmd.Flags().String("format-type", "MARKDOWN", "MARKDOWN|RICHTEXT")
	workitemCommentCmd.Flags().String("id", "", "work item id (required)")
	workitemCommentCmd.Flags().String("content", "", "comment content (or use --content-file)")
	workitemCommentCmd.Flags().String("content-file", "", "UTF-8 file for comment body (BOM stripped; preferred on Windows for Chinese)")
	workitemCreateCmd.Flags().String("space-id", "", "project/space id (required)")
	workitemCreateCmd.Flags().String("type-id", "", "work item type id (required)")
	workitemCreateCmd.Flags().String("subject", "", "title (required unless --subject-file)")
	workitemCreateCmd.Flags().String("subject-file", "", "UTF-8 file for title (BOM stripped; preferred on Windows for Chinese)")
	workitemCreateCmd.Flags().String("assigned-to", "", "assignee user id or self (required)")
	workitemCreateCmd.Flags().String("description", "", "description (or use --description-file)")
	workitemCreateCmd.Flags().String("description-file", "", "UTF-8 file for description (BOM stripped; preferred on Windows for Chinese)")
	workitemCreateCmd.Flags().String("format-type", "", "RICHTEXT|MARKDOWN")
	workitemCreateCmd.Flags().String("parent-id", "", "parent work item id")
	workitemCreateCmd.Flags().String("sprint", "", "sprint id (omit if type has not enabled 迭代)")
	workitemCreateCmd.Flags().String("labels", "", "comma-separated label ids")
	workitemCreateCmd.Flags().String("participants", "", "comma-separated user ids")
	workitemCreateCmd.Flags().String("trackers", "", "comma-separated user ids")
	workitemCreateCmd.Flags().String("verifier", "", "verifier user id or self")
	workitemCreateCmd.Flags().String("versions", "", "comma-separated version ids")
	workitemCreateCmd.Flags().String("custom-fields", "", "JSON object of customFieldValues (fieldId to value); mutually exclusive with --custom-fields-file")
	workitemCreateCmd.Flags().String("custom-fields-file", "", "UTF-8 JSON object file for customFieldValues (BOM stripped; preferred on Windows for Chinese)")
	workitemCreateCmd.Flags().Bool("no-defaults", false, "skip profile workitem_defaults for this type")
	workitemCreateCmd.Flags().Bool("no-precheck", false, "skip the required-field precheck (no GET .../fields before create)")
	workitemCreateCmd.Flags().Bool("full", false, "print full create JSON (default: brief id/serialNumber/status/subject)")
	workitemUpdateCmd.Flags().String("id", "", "work item id (required)")
	workitemUpdateCmd.Flags().String("subject", "", "new subject")
	workitemUpdateCmd.Flags().String("status", "", "status id")
	workitemUpdateCmd.Flags().String("assigned-to", "", "assignee user id or self")
	workitemUpdateCmd.Flags().String("priority", "", "priority id")
	workitemUpdateCmd.Flags().String("description", "", "description")
	workitemUpdateCmd.Flags().String("labels", "", "comma-separated label ids")
	workitemUpdateCmd.Flags().String("sprint", "", "sprint id")
	workitemUpdateCmd.Flags().String("verifier", "", "verifier user id or self")
	workitemUpdateCmd.Flags().String("participants", "", "comma-separated user ids")
	workitemUpdateCmd.Flags().String("trackers", "", "comma-separated user ids")
	workitemUpdateCmd.Flags().String("versions", "", "comma-separated version ids")
	workitemUpdateCmd.Flags().String("custom-fields", "", "JSON object of custom fields (merged onto body like MCP)")
	workitemUpdateCmd.Flags().String("cancel-reason", "", "set 取消原因 custom field (looked up on item type); useful with --status 已取消/141230")
	workitemRelationsListCmd.Flags().String("id", "", "work item id (required)")
	workitemRelationsListCmd.Flags().String("relation-type", "", "relation type (required); e.g. ASSOCIATED, DEPEND_ON")
	workitemRelationsCreateCmd.Flags().String("id", "", "work item id (required)")
	workitemRelationsCreateCmd.Flags().String("related-id", "", "related work item id (required)")
	workitemRelationsCreateCmd.Flags().String("relation-type", "", "relation type (required); e.g. ASSOCIATED, DEPEND_ON (RELATED/PARENT_SUB often fail)")
	workitemRelationsDeleteCmd.Flags().String("id", "", "work item id (required)")
	workitemRelationsDeleteCmd.Flags().String("related-id", "", "related work item id (required)")
	workitemRelationsDeleteCmd.Flags().String("relation-type", "", "relation type (required); e.g. ASSOCIATED, DEPEND_ON")
	workitemDeleteCmd.Flags().String("id", "", "work item id (required)")
	workitemFieldsCmd.Flags().String("space-id", "", "project/space id (required)")
	workitemFieldsCmd.Flags().String("type-id", "", "work item type id (required)")
	workitemWorkflowCmd.Flags().String("space-id", "", "project/space id (required)")
	workitemWorkflowCmd.Flags().String("type-id", "", "work item type id (required)")
	workitemStatusesCmd.Flags().String("space-id", "", "project/space id (required)")
	workitemStatusesCmd.Flags().String("type-id", "", "work item type id (required)")
	workitemActivitiesCmd.Flags().String("id", "", "work item id (required)")
	addSortFlag(workitemActivitiesCmd)
	workitemTypesListCmd.Flags().String("space-id", "", "project/space id (required)")
	workitemTypesListCmd.Flags().String("category", "", "Req|Bug|Task|Risk|Topic|all (default: fetch every category and merge, #99)")
	workitemCommentsCmd.AddCommand(workitemCommentsListCmd, workitemCommentsDeleteCmd, workitemCommentsUpdateCmd)
	workitemAttachmentsListCmd.Flags().String("id", "", "work item id (required)")
	workitemAttachmentsCreateCmd.Flags().String("id", "", "work item id (required)")
	workitemAttachmentsCreateCmd.Flags().String("file", "", "relative file path (required)")
	workitemAttachmentsCreateCmd.Flags().String("file-name", "", "override filename (default basename)")
	workitemAttachmentsCreateCmd.Flags().String("operator-id", "", "operator user id (app token)")
	workitemRelationsCmd.AddCommand(workitemRelationsListCmd, workitemRelationsCreateCmd, workitemRelationsDeleteCmd)
	workitemAttachmentsCmd.AddCommand(workitemAttachmentsListCmd, workitemAttachmentsCreateCmd)
	workitemTypesCmd.AddCommand(workitemTypesListCmd)
	workitemCmd.AddCommand(workitemSearchCmd, workitemGetCmd, workitemCommentsCmd, workitemCommentCmd, workitemCreateCmd, workitemUpdateCmd, workitemDeleteCmd, workitemRelationsCmd, workitemAttachmentsCmd, workitemFieldsCmd, workitemWorkflowCmd, workitemStatusesCmd, workitemActivitiesCmd, workitemTypesCmd)
}
