package schema

import "github.com/yunxiao-cli/yunxiao/internal/risk"

type Method struct {
	ID          string     `json:"id"`
	Domain      string     `json:"domain"`
	Description string     `json:"description"`
	HTTPMethod  string     `json:"http_method"`
	Path        string     `json:"path"`
	Risk        risk.Level `json:"risk"`
	Params      []Param    `json:"params,omitempty"`
	Example     string     `json:"example,omitempty"`
}

type Param struct {
	Name     string `json:"name"`
	Type     string `json:"type"`
	Required bool   `json:"required"`
	Desc     string `json:"description"`
}

var Registry = []Method{
	{ID: "organization.user.get", Domain: "organization", Description: "Get current user / last organization",
		HTTPMethod: "GET", Path: "/oapi/v1/platform/user", Risk: risk.Read, Example: "yunxiao organization user get"},
	{ID: "organization.list", Domain: "organization", Description: "List organizations",
		HTTPMethod: "GET", Path: "/oapi/v1/platform/organizations", Risk: risk.Read, Example: "yunxiao organization list"},
	{ID: "organization.members.list", Domain: "organization", Description: "List organization members",
		HTTPMethod: "GET", Path: "/oapi/v1/platform/organizations/{org}/members", Risk: risk.Read, Example: "yunxiao organization members list"},
	{ID: "organization.members.search", Domain: "organization", Description: "Search organization members",
		HTTPMethod: "POST", Path: "/oapi/v1/platform/organizations/{org}/members:search", Risk: risk.Read, Example: "yunxiao organization members search --query alice"},
	{ID: "project.list", Domain: "project", Description: "Search / list Projex projects",
		HTTPMethod: "POST", Path: "/oapi/v1/projex/organizations/{org}/projects:search", Risk: risk.Read, Example: "yunxiao project list --name demo"},
	{ID: "workitem.search", Domain: "project", Description: "Search work items (date/status filters, --all, opt-in --as-items; client-filter dates if needed)",
		HTTPMethod: "POST", Path: "/oapi/v1/projex/organizations/{org}/workitems:search", Risk: risk.Read,
		Params: []Param{
			{Name: "category", Type: "string", Required: true, Desc: "Req|Bug|Task|…"},
			{Name: "space-id", Type: "string", Required: false, Desc: "project/space id (default profile.space_id)"},
			{Name: "assigned-to", Type: "string", Required: false, Desc: "assignee user id or self"},
			{Name: "creator", Type: "string", Required: false, Desc: "creator user id or self"},
			{Name: "subject", Type: "string", Required: false, Desc: "subject contains"},
			{Name: "status", Type: "string", Required: false, Desc: "status ids CSV (className status)"},
			{Name: "status-stage", Type: "string", Required: false, Desc: "statusStage ids CSV"},
			{Name: "created-after", Type: "string", Required: false, Desc: "gmtCreate >= YYYY-MM-DD HH:MM:SS (inclusive; server may still return out-of-window — client-filter)"},
			{Name: "created-before", Type: "string", Required: false, Desc: "gmtCreate <="},
			{Name: "updated-after", Type: "string", Required: false, Desc: "gmtModified >="},
			{Name: "updated-before", Type: "string", Required: false, Desc: "gmtModified <="},
			{Name: "finish-after", Type: "string", Required: false, Desc: "finishTime >= (filter; response may omit field)"},
			{Name: "finish-before", Type: "string", Required: false, Desc: "finishTime <="},
			{Name: "page", Type: "int", Required: false, Desc: "page (default 1)"},
			{Name: "per-page", Type: "int", Required: false, Desc: "per page (OpenAPI max 200)"},
			{Name: "all", Type: "bool", Required: false, Desc: "follow pages (ListAll max 50); dedupe by id"},
			{Name: "as-items", Type: "bool", Required: false, Desc: "opt-in wrap data as {items, pagination} for scripts"},
		},
		Example: `yunxiao workitem search --category Req --created-after "2026-09-01 00:00:00" --created-before "2026-09-07 23:59:59" --status-stage 1,2 --all --as-items`},
	{ID: "workitem.get", Domain: "project", Description: "Get a work item by ID",
		HTTPMethod: "GET", Path: "/oapi/v1/projex/organizations/{org}/workitems/{id}", Risk: risk.Read,
		Params: []Param{{Name: "id", Type: "string", Required: true, Desc: "Work item ID"}}, Example: "yunxiao workitem get --id <id>"},
	{ID: "workitem.comments.list", Domain: "project", Description: "List work item comments (OAPI personal-token). Delete/update via AccessKey RPC commands.",
		HTTPMethod: "GET", Path: "/oapi/v1/projex/organizations/{org}/workitems/{id}/comments", Risk: risk.Read, Example: "yunxiao workitem comments list --id <id>"},
	{ID: "workitem.comments.delete", Domain: "project", Description: "Delete work item comment via AccessKey RPC DeleteWorkitemComment (POST .../deleteComent). Requires ALIBABA_CLOUD_ACCESS_KEY_* + --yes",
		HTTPMethod: "POST", Path: "https://devops.{region}.aliyuncs.com/organization/{org}/workitems/deleteComent", Risk: risk.HighRiskWrite,
		Params: []Param{
			{Name: "id", Type: "string", Required: true, Desc: "work item id or serial"},
			{Name: "comment-id", Type: "string", Required: true, Desc: "comment id (positive int)"},
		},
		Example: "yunxiao workitem comments delete --id <id|serial> --comment-id <cid> --dry-run"},
	{ID: "workitem.comments.update", Domain: "project", Description: "Update work item comment via AccessKey RPC UpdateWorkitemComment (POST .../commentUpdate). Requires ALIBABA_CLOUD_ACCESS_KEY_*",
		HTTPMethod: "POST", Path: "https://devops.{region}.aliyuncs.com/organization/{org}/workitems/commentUpdate", Risk: risk.Write,
		Params: []Param{
			{Name: "id", Type: "string", Required: true, Desc: "work item id or serial"},
			{Name: "comment-id", Type: "string", Required: true, Desc: "comment id"},
			{Name: "content", Type: "string", Required: false, Desc: "new text; mutually exclusive with content-file"},
			{Name: "content-file", Type: "string", Required: false, Desc: "UTF-8 file (BOM stripped)"},
			{Name: "format-type", Type: "string", Required: false, Desc: "MARKDOWN|RICHTEXT (default MARKDOWN)"},
		},
		Example: "yunxiao workitem comments update --id <id> --comment-id <cid> --content-file ./note.md --dry-run"},
	{ID: "workitem.comment", Domain: "project", Description: "Add a work item comment (--content or --content-file UTF-8). OAPI create; delete/update are AccessKey RPC subcommands",
		HTTPMethod: "POST", Path: "/oapi/v1/projex/organizations/{org}/workitems/{id}/comments", Risk: risk.Write,
		Params: []Param{
			{Name: "id", Type: "string", Required: true},
			{Name: "content", Type: "string", Required: false, Desc: "comment text; mutually exclusive with content-file"},
			{Name: "content-file", Type: "string", Required: false, Desc: "UTF-8 file path (BOM stripped); preferred on Windows for Chinese"},
		},
		Example: "yunxiao workitem comment --id <id> --content-file ./note.md --dry-run"},
	{ID: "codeup.repos.list", Domain: "codeup", Description: "List Codeup repositories",
		HTTPMethod: "GET", Path: "/oapi/v1/codeup/organizations/{org}/repositories", Risk: risk.Read, Example: "yunxiao codeup repos list"},
	{ID: "codeup.branches.list", Domain: "codeup", Description: "List branches",
		HTTPMethod: "GET", Path: "/oapi/v1/codeup/organizations/{org}/repositories/{repo}/branches", Risk: risk.Read, Example: "yunxiao codeup branches list --repo <id>"},
	{ID: "codeup.files.tree", Domain: "codeup", Description: "List file tree",
		HTTPMethod: "GET", Path: "/oapi/v1/codeup/organizations/{org}/repositories/{repo}/files/tree", Risk: risk.Read, Example: "yunxiao codeup files tree --repo <id> --ref master"},
	{ID: "codeup.files.get", Domain: "codeup", Description: "Get file content",
		HTTPMethod: "GET", Path: "/oapi/v1/codeup/organizations/{org}/repositories/{repo}/files/{path}", Risk: risk.Read, Example: "yunxiao codeup files get --repo <id> --path README.md --ref master"},
	{ID: "codeup.commits.list", Domain: "codeup", Description: "List commits",
		HTTPMethod: "GET", Path: "/oapi/v1/codeup/organizations/{org}/repositories/{repo}/commits", Risk: risk.Read, Example: "yunxiao codeup commits list --repo <id> --ref master"},
	{ID: "codeup.mrs.list", Domain: "codeup", Description: "List merge requests",
		HTTPMethod: "GET", Path: "/oapi/v1/codeup/organizations/{org}/changeRequests", Risk: risk.Read, Example: "yunxiao codeup mrs list --state opened"},
	{ID: "codeup.mrs.create", Domain: "codeup", Description: "Create a merge request",
		HTTPMethod: "POST", Path: "/oapi/v1/codeup/organizations/{org}/repositories/{repo}/changeRequests", Risk: risk.HighRiskWrite,
		Params: []Param{
			{Name: "repo", Type: "string", Required: true, Desc: "repository id or alias"},
			{Name: "source", Type: "string", Required: true, Desc: "source branch"},
			{Name: "target", Type: "string", Required: true, Desc: "target branch"},
			{Name: "title", Type: "string", Required: true, Desc: "MR title"},
			{Name: "description", Type: "string", Required: false, Desc: "MR description"},
			{Name: "reviewer", Type: "string", Required: false, Desc: "comma-separated reviewer userIds → body reviewerUserIds (same as mrs +create)"},
			{Name: "create-from", Type: "string", Required: false, Desc: "createFrom, default WEB"},
		},
		Example: "yunxiao codeup mrs create --repo <id> --source feature --target master --title 'x' --reviewer <userId> --dry-run"},
	{ID: "pipeline.list", Domain: "pipeline", Description: "List Flow pipelines",
		HTTPMethod: "GET", Path: "/oapi/v1/flow/organizations/{org}/pipelines", Risk: risk.Read, Example: "yunxiao pipeline list"},
	{ID: "pipeline.run.list", Domain: "pipeline", Description: "List pipeline runs",
		HTTPMethod: "GET", Path: "/oapi/v1/flow/organizations/{org}/pipelines/{id}/runs", Risk: risk.Read, Example: "yunxiao pipeline run list --pipeline-id <id>"},
	{ID: "pipeline.run.latest", Domain: "pipeline", Description: "Get latest pipeline run",
		HTTPMethod: "GET", Path: "/oapi/v1/flow/organizations/{org}/pipelines/{id}/runs/latestPipelineRun", Risk: risk.Read, Example: "yunxiao pipeline run latest --pipeline-id <id>"},
	{ID: "pipeline.run.get", Domain: "pipeline", Description: "Get pipeline run by id",
		HTTPMethod: "GET", Path: "/oapi/v1/flow/organizations/{org}/pipelines/{id}/runs/{runId}", Risk: risk.Read, Example: "yunxiao pipeline run get --pipeline-id <id> --run-id <rid>"},
	{ID: "pipeline.run.failed", Domain: "pipeline", Description: "Summarize failed runs",
		HTTPMethod: "GET", Path: "/oapi/v1/flow/organizations/{org}/pipelines/{id}/runs?status=FAIL", Risk: risk.Read, Example: "yunxiao pipeline run failed --pipeline-id <id>"},
	{ID: "pipeline.job.log", Domain: "pipeline", Description: "Get job run log",
		HTTPMethod: "GET", Path: "/oapi/v1/flow/organizations/{org}/pipelines/{id}/runs/{runId}/job/{jobId}/log", Risk: risk.Read,
		Example: "yunxiao pipeline job log --pipeline-id <id> --run-id <rid> --job-id <jid>"},
	{ID: "packages.repos.list", Domain: "packages", Description: "List package repositories",
		HTTPMethod: "GET", Path: "/oapi/v1/packages/organizations/{org}/repositories", Risk: risk.Read, Example: "yunxiao packages repos list"},
	{ID: "codeup.files.create", Domain: "codeup", Description: "Create a file",
		HTTPMethod: "POST", Path: "/oapi/v1/codeup/organizations/{org}/repositories/{repo}/files", Risk: risk.HighRiskWrite,
		Example: "yunxiao codeup files create --repo <id> --path a.txt --branch master --message 'add' --content 'x' --dry-run"},
	{ID: "codeup.files.update", Domain: "codeup", Description: "Update a file",
		HTTPMethod: "PUT", Path: "/oapi/v1/codeup/organizations/{org}/repositories/{repo}/files/{path}", Risk: risk.HighRiskWrite,
		Example: "yunxiao codeup files update --repo <id> --path a.txt --branch master --message 'upd' --content 'y' --dry-run"},
	{ID: "pipeline.run.trigger", Domain: "pipeline", Description: "Trigger a pipeline run",
		HTTPMethod: "POST", Path: "/oapi/v1/flow/organizations/{org}/pipelines/{id}/runs", Risk: risk.HighRiskWrite,
		Example: "yunxiao pipeline run trigger --pipeline-id <id> --branch master --dry-run"},
	{ID: "pipeline.job.stop", Domain: "pipeline", Description: "Stop a pipeline job",
		HTTPMethod: "PUT", Path: "/oapi/v1/flow/organizations/{org}/pipelines/{id}/pipelineRuns/{runId}/jobs/{jobId}/stop", Risk: risk.HighRiskWrite,
		Example: "yunxiao pipeline job stop --pipeline-id <id> --run-id <rid> --job-id <jid> --dry-run"},
	{ID: "packages.artifacts.list", Domain: "packages", Description: "List artifacts",
		HTTPMethod: "GET", Path: "/oapi/v1/packages/organizations/{org}/repositories/{repoId}/artifacts", Risk: risk.Read,
		Example: "yunxiao packages artifacts list --repo-id <id> --repo-type GENERIC"},
	{ID: "packages.artifacts.get", Domain: "packages", Description: "Get artifact",
		HTTPMethod: "GET", Path: "/oapi/v1/packages/organizations/{org}/repositories/{repoId}/artifacts/{id}", Risk: risk.Read,
		Example: "yunxiao packages artifacts get --repo-id <id> --repo-type GENERIC --id <aid>"},
	{ID: "workitem.update", Domain: "project", Description: "Update work item fields",
		HTTPMethod: "PUT", Path: "/oapi/v1/projex/organizations/{org}/workitems/{id}", Risk: risk.Write,
		Example: "yunxiao workitem update --id <id> --assigned-to self --dry-run"},
	{ID: "testhub.plans.list", Domain: "testhub", Description: "List test plans",
		HTTPMethod: "POST", Path: "/oapi/v1/projex/organizations/{org}/testPlan/list", Risk: risk.Read,
		Example: "yunxiao testhub plans list --project-id <id>"},
	{ID: "testhub.repos.list", Domain: "testhub", Description: "List test repos",
		HTTPMethod: "GET", Path: "/oapi/v1/testhub/organizations/{org}/testRepo/list", Risk: risk.Read,
		Example: "yunxiao testhub repos list"},
	{ID: "appstack.apps.list", Domain: "appstack", Description: "List AppStack apps",
		HTTPMethod: "GET", Path: "/oapi/v1/appstack/organizations/{org}/apps:search", Risk: risk.Read,
		Example: "yunxiao appstack apps list"},
	{ID: "appstack.apps.get", Domain: "appstack", Description: "Get AppStack app",
		HTTPMethod: "GET", Path: "/oapi/v1/appstack/organizations/{org}/apps/{name}", Risk: risk.Read,
		Example: "yunxiao appstack apps get --name my-app"},
	{ID: "workitem.create", Domain: "project", Description: "Create a work item",
		HTTPMethod: "POST", Path: "/oapi/v1/projex/organizations/{org}/workitems", Risk: risk.Write,
		Example: "yunxiao workitem create --space-id <id> --type-id <tid> --subject 'x' --assigned-to self --dry-run"},
	{ID: "codeup.files.delete", Domain: "codeup", Description: "Delete a file",
		HTTPMethod: "DELETE", Path: "/oapi/v1/codeup/organizations/{org}/repositories/{repo}/files/{path}", Risk: risk.HighRiskWrite,
		Example: "yunxiao codeup files delete --repo <id> --path a.txt --branch master --message 'rm' --dry-run"},
	{ID: "codeup.mrs.merge", Domain: "codeup", Description: "Merge a merge request",
		HTTPMethod: "POST", Path: "/oapi/v1/codeup/organizations/{org}/repositories/{repo}/changeRequests/{id}/merge", Risk: risk.HighRiskWrite,
		Example: "yunxiao codeup mrs merge --repo <id> --local-id 1 --merge-type no-fast-forward --dry-run"},
	{ID: "codeup.mrs.close", Domain: "codeup", Description: "Close a merge request",
		HTTPMethod: "POST", Path: "/oapi/v1/codeup/organizations/{org}/repositories/{repo}/changeRequests/{id}/close", Risk: risk.HighRiskWrite,
		Example: "yunxiao codeup mrs close --repo <id> --local-id 1 --dry-run"},
	{ID: "codeup.mrs.review", Domain: "codeup", Description: "Review a merge request",
		HTTPMethod: "POST", Path: "/oapi/v1/codeup/organizations/{org}/repositories/{repo}/changeRequests/{id}/review", Risk: risk.HighRiskWrite,
		Example: "yunxiao codeup mrs review --repo <id> --local-id 1 --opinion PASS --dry-run"},
	{ID: "pipeline.run.cancel", Domain: "pipeline", Description: "Cancel an entire pipeline run",
		HTTPMethod: "PUT", Path: "/oapi/v1/flow/organizations/{org}/pipelines/{id}/runs/{runId}", Risk: risk.HighRiskWrite,
		Example: "yunxiao pipeline run cancel --pipeline-id <id> --run-id <rid> --dry-run"},
	{ID: "testhub.plans.progress", Domain: "testhub", Description: "Test plan progress",
		HTTPMethod: "GET", Path: "/oapi/v1/testhub/organizations/{org}/{planId}/progressRate", Risk: risk.Read,
		Example: "yunxiao testhub plans progress --plan-id <id>"},
	{ID: "testhub.plans.directories", Domain: "testhub", Description: "Test plan result directories",
		HTTPMethod: "GET", Path: "/oapi/v1/testhub/organizations/{org}/{planId}/result/directory/list", Risk: risk.Read,
		Example: "yunxiao testhub plans directories --plan-id <id>"},
	{ID: "testhub.results.list", Domain: "testhub", Description: "List test results in a directory",
		HTTPMethod: "POST", Path: "/oapi/v1/testhub/organizations/{org}/{planId}/result/list/{dirId}", Risk: risk.Read,
		Example: "yunxiao testhub results list --plan-id <id> --directory-id <dir>"},
	{ID: "appstack.change_orders.versions", Domain: "appstack", Description: "List change order versions",
		HTTPMethod: "GET", Path: "/oapi/v1/appstack/organizations/{org}/apps/{app}/changeOrders/versions", Risk: risk.Read,
		Example: "yunxiao appstack change-orders versions --app my-app"},
	{ID: "appstack.change_orders.get", Domain: "appstack", Description: "Get change order",
		HTTPMethod: "GET", Path: "/oapi/v1/appstack/organizations/{org}/apps/{app}/changeOrders/{sn}", Risk: risk.Read,
		Example: "yunxiao appstack change-orders get --app my-app --sn <sn>"},
	{ID: "appstack.change_orders.by_origin", Domain: "appstack", Description: "List change orders by origin",
		HTTPMethod: "GET", Path: "/oapi/v1/appstack/organizations/{org}/changeOrders:byOrigin", Risk: risk.Read,
		Example: "yunxiao appstack change-orders by-origin --origin-type X --origin-id Y"},
	{ID: "codeup.mrs.get", Domain: "codeup", Description: "Get merge request",
		HTTPMethod: "GET", Path: ".../changeRequests/{localId}", Risk: risk.Read,
		Example: "yunxiao codeup mrs get --repo <id> --local-id 1 --brief"},
	{ID: "codeup.mrs.update", Domain: "codeup", Description: "Update MR title/description and/or link work items",
		HTTPMethod: "PUT", Path: ".../changeRequests/{localId}", Risk: risk.Write,
		Example: "yunxiao codeup mrs update --repo <id> --local-id 1 --title \"WIP: x\" --work-item ZYPT-1 --dry-run"},
	{ID: "codeup.mrs.link", Domain: "codeup", Description: "Link work items to an existing MR via extRelationRecords",
		HTTPMethod: "POST", Path: ".../workitems/{id}/extRelationRecords", Risk: risk.Write,
		Example: "yunxiao codeup mrs link --repo <id> --local-id 1 --work-item ZYPT-1 --dry-run"},
	{ID: "codeup.mrs.unlink", Domain: "codeup", Description: "Unlink work items from an existing MR via extRelationRecords",
		HTTPMethod: "DELETE", Path: ".../workitems/{id}/extRelationRecords/{relationRecordId}", Risk: risk.Write,
		Example: "yunxiao codeup mrs unlink --repo <id> --local-id 1 --work-item ZYPT-1 --dry-run"},
	{ID: "codeup.mrs.diffs", Domain: "codeup", Description: "List MR patch sets",
		HTTPMethod: "GET", Path: ".../changeRequests/{localId}/diffs/patches", Risk: risk.Read,
		Example: "yunxiao codeup mrs diffs --repo <id> --local-id 1"},
	{ID: "codeup.mrs.reopen", Domain: "codeup", Description: "Reopen MR",
		HTTPMethod: "POST", Path: ".../changeRequests/{localId}/reopen", Risk: risk.HighRiskWrite,
		Example: "yunxiao codeup mrs reopen --repo <id> --local-id 1 --dry-run"},
	{ID: "codeup.compare", Domain: "codeup", Description: "Compare refs",
		HTTPMethod: "GET", Path: ".../repositories/{repo}/compares", Risk: risk.Read,
		Example: "yunxiao codeup compare --repo <id> --from master --to feature"},
	{ID: "pipeline.job.retry", Domain: "pipeline", Description: "Retry job",
		HTTPMethod: "PUT", Path: ".../jobs/{jobId}/retry", Risk: risk.HighRiskWrite,
		Example: "yunxiao pipeline job retry --pipeline-id <id> --run-id <r> --job-id <j> --dry-run"},
	{ID: "pipeline.job.skip", Domain: "pipeline", Description: "Skip job",
		HTTPMethod: "PUT", Path: ".../jobs/{jobId}/skip", Risk: risk.HighRiskWrite,
		Example: "yunxiao pipeline job skip --pipeline-id <id> --run-id <r> --job-id <j> --dry-run"},
	{ID: "pipeline.job.rerun", Domain: "pipeline", Description: "Rerun job",
		HTTPMethod: "PUT", Path: ".../jobs/{jobId}/rerun", Risk: risk.HighRiskWrite,
		Example: "yunxiao pipeline job rerun --pipeline-id <id> --run-id <r> --job-id <j> --dry-run"},
	{ID: "packages.artifacts.delete", Domain: "packages", Description: "Delete artifact",
		HTTPMethod: "DELETE", Path: ".../artifacts/{id}", Risk: risk.HighRiskWrite,
		Example: "yunxiao packages artifacts delete --repo-id <id> --repo-type GENERIC --id <aid> --dry-run"},
	{ID: "workitem.delete", Domain: "project", Description: "Delete work item",
		HTTPMethod: "DELETE", Path: ".../workitems/{id}", Risk: risk.HighRiskWrite,
		Example: "yunxiao workitem delete --id <id> --dry-run"},
	{ID: "workitem.types.list", Domain: "project", Description: "List work item types",
		HTTPMethod: "GET", Path: ".../projects/{space}/workitemTypes", Risk: risk.Read,
		Example: "yunxiao workitem types list --space-id <id> --category Req"},
	{ID: "appstack.change_orders.create", Domain: "appstack", Description: "Create change order",
		HTTPMethod: "POST", Path: ".../apps/{app}/changeOrders", Risk: risk.HighRiskWrite,
		Example: "yunxiao appstack change-orders create --app my-app --data '{...}' --dry-run"},
	{ID: "appstack.change_orders.execute_job", Domain: "appstack", Description: "Execute job action",
		HTTPMethod: "PUT", Path: ".../jobs/{jobSn}:execute", Risk: risk.HighRiskWrite,
		Example: "yunxiao appstack change-orders execute-job --app a --sn s --job-sn j --action-type STOP --dry-run"},
	{ID: "codeup.mrs.comments.list", Domain: "codeup", Description: "List MR comments",
		HTTPMethod: "POST", Path: ".../changeRequests/{localId}/comments/list", Risk: risk.Read,
		Example: "yunxiao codeup mrs comments list --repo <id> --local-id 1"},
	{ID: "codeup.mrs.comments.create", Domain: "codeup", Description: "Create MR comment",
		HTTPMethod: "POST", Path: ".../changeRequests/{localId}/comments", Risk: risk.Write,
		Example: "yunxiao codeup mrs comments create --repo <id> --local-id 1 --content note --patchset-biz-id <biz> --dry-run"},
	{ID: "codeup.mrs.comments.resolve", Domain: "codeup", Description: "Resolve MR comment",
		HTTPMethod: "PUT", Path: ".../changeRequests/{localId}/comments/{commentBizId}", Risk: risk.Write,
		Example: "yunxiao codeup mrs comments resolve --repo <id> --local-id 1 --comment-biz-id <biz> --dry-run"},
	{ID: "codeup.mrs.comments.reopen", Domain: "codeup", Description: "Reopen MR comment",
		HTTPMethod: "PUT", Path: ".../changeRequests/{localId}/comments/{commentBizId}", Risk: risk.Write,
		Example: "yunxiao codeup mrs comments reopen --repo <id> --local-id 1 --comment-biz-id <biz> --dry-run"},
	{ID: "codeup.mrs.labels.list", Domain: "codeup", Description: "List MR labels",
		HTTPMethod: "GET", Path: ".../changeRequests/{localId}/labels", Risk: risk.Read,
		Example: "yunxiao codeup mrs labels list --repo <id> --local-id 1"},
	{ID: "codeup.mrs.labels.attach", Domain: "codeup", Description: "Attach labels to MR",
		HTTPMethod: "POST", Path: ".../changeRequests/{localId}/labels", Risk: risk.Write,
		Example: "yunxiao codeup mrs labels attach --repo <id> --local-id 1 --label-ids 1,2 --dry-run"},
	{ID: "codeup.mrs.reviewers.add", Domain: "codeup", Description: "Add/update reviewers on an existing MR",
		HTTPMethod: "POST", Path: ".../changeRequests/{localId}/person/REVIEWER", Risk: risk.Write,
		Params: []Param{
			{Name: "repo", Type: "string", Required: true, Desc: "repository id or alias"},
			{Name: "local-id", Type: "string", Required: true, Desc: "MR local id"},
			{Name: "reviewer", Type: "string", Required: true, Desc: "comma-separated reviewer userIds → body userIds (person/REVIEWER)"},
		},
		Example: "yunxiao codeup mrs reviewers add --repo <id> --local-id 1 --reviewer <userId1,userId2> --dry-run"},
	{ID: "pipeline.job.pass", Domain: "pipeline", Description: "Pass manual validation gate",
		HTTPMethod: "POST", Path: ".../jobs/{jobId}/pass", Risk: risk.HighRiskWrite,
		Example: "yunxiao pipeline job pass --pipeline-id <id> --run-id <r> --job-id <j> --dry-run"},
	{ID: "pipeline.job.refuse", Domain: "pipeline", Description: "Refuse manual validation gate",
		HTTPMethod: "POST", Path: ".../jobs/{jobId}/refuse", Risk: risk.HighRiskWrite,
		Example: "yunxiao pipeline job refuse --pipeline-id <id> --run-id <r> --job-id <j> --dry-run"},
	{ID: "testhub.results.update", Domain: "testhub", Description: "Update plan testcase result",
		HTTPMethod: "PUT", Path: ".../testPlans/{plan}/testcases/{id}", Risk: risk.Write,
		Example: "yunxiao testhub results update --plan-id <p> --testcase-id <t> --status PASSED --dry-run"},
	{ID: "testhub.plan_comments.list", Domain: "testhub", Description: "List plan testcase comments",
		HTTPMethod: "GET", Path: ".../testPlans/{plan}/testcases/{id}/comments", Risk: risk.Read,
		Example: "yunxiao testhub plan-comments list --plan-id <p> --testcase-id <t>"},
	{ID: "testhub.plan_comments.create", Domain: "testhub", Description: "Create plan testcase comment",
		HTTPMethod: "POST", Path: ".../testPlans/{plan}/testcases/{id}/comments", Risk: risk.Write,
		Example: "yunxiao testhub plan-comments create --plan-id <p> --testcase-id <t> --content note --dry-run"},
	{ID: "workitem.relations.list", Domain: "project", Description: "List work item relations",
		HTTPMethod: "GET", Path: ".../workitems/{id}/relationRecords", Risk: risk.Read,
		Example: "yunxiao workitem relations list --id <id> --relation-type ASSOCIATED"},
	{ID: "workitem.relations.create", Domain: "project", Description: "Create work item relation",
		HTTPMethod: "POST", Path: ".../workitems/{id}/relationRecords", Risk: risk.Write,
		Example: "yunxiao workitem relations create --id <id> --related-id <rid> --relation-type ASSOCIATED --dry-run"},
	{ID: "workitem.relations.delete", Domain: "project", Description: "Delete work item relation",
		HTTPMethod: "DELETE", Path: ".../workitems/{id}/relationRecords", Risk: risk.Write,
		Example: "yunxiao workitem relations delete --id <id> --related-id <rid> --relation-type ASSOCIATED --dry-run"},
	{ID: "appstack.change_orders.job_logs", Domain: "appstack", Description: "List change-order job logs",
		HTTPMethod: "GET", Path: ".../changeOrders/{sn}/jobs/{jobSn}/logs", Risk: risk.Read,
		Example: "yunxiao appstack change-orders job-logs --app a --sn s --job-sn j"},
	{ID: "appstack.orchestrations.list", Domain: "appstack", Description: "List app orchestrations",
		HTTPMethod: "GET", Path: ".../apps/{app}/orchestrations", Risk: risk.Read,
		Example: "yunxiao appstack orchestrations list --app my-app"},
	{ID: "appstack.orchestrations.get", Domain: "appstack", Description: "Get app orchestration",
		HTTPMethod: "GET", Path: ".../apps/{app}/orchestrations/{sn}", Risk: risk.Read,
		Example: "yunxiao appstack orchestrations get --app my-app --sn <sn>"},
	{ID: "pipeline.get", Domain: "pipeline", Description: "Get pipeline detail",
		HTTPMethod: "GET", Path: ".../pipelines/{id}", Risk: risk.Read,
		Example: "yunxiao pipeline get --id <id>"},
	{ID: "pipeline.create", Domain: "pipeline", Description: "Create pipeline from YAML",
		HTTPMethod: "POST", Path: ".../pipelines", Risk: risk.HighRiskWrite,
		Example: "yunxiao pipeline create --name ci --file pipeline.yaml --dry-run"},
	{ID: "pipeline.update", Domain: "pipeline", Description: "Update pipeline YAML",
		HTTPMethod: "PUT", Path: ".../pipelines/{id}", Risk: risk.HighRiskWrite,
		Example: "yunxiao pipeline update --id <id> --name ci --file pipeline.yaml --dry-run"},
	{ID: "workitem.attachments.list", Domain: "project", Description: "List work item attachments",
		HTTPMethod: "GET", Path: ".../workitems/{id}/attachments", Risk: risk.Read,
		Example: "yunxiao workitem attachments list --id <id>"},
	{ID: "workitem.attachments.create", Domain: "project", Description: "Upload work item attachment",
		HTTPMethod: "POST", Path: ".../workitems/{id}/attachments (multipart)", Risk: risk.Write,
		Example: "yunxiao workitem attachments create --id <id> --file ./a.png --dry-run"},
	{ID: "appstack.tags.search", Domain: "appstack", Description: "Search app tags",
		HTTPMethod: "POST", Path: ".../appTags:search", Risk: risk.Read,
		Example: "yunxiao appstack tags search --search demo"},
	{ID: "appstack.tags.create", Domain: "appstack", Description: "Create app tag",
		HTTPMethod: "POST", Path: ".../appTags", Risk: risk.HighRiskWrite,
		Example: "yunxiao appstack tags create --name t --color '#4676e5' --dry-run"},
	{ID: "appstack.tags.bind", Domain: "appstack", Description: "Bind tags to app",
		HTTPMethod: "PUT", Path: ".../apps/{app}/appTags", Risk: risk.HighRiskWrite,
		Example: "yunxiao appstack tags bind --app a --tag-names t1,t2 --dry-run"},
	{ID: "appstack.variable_groups.list", Domain: "appstack", Description: "List app variable groups",
		HTTPMethod: "GET", Path: ".../apps/{app}/variableGroups", Risk: risk.Read,
		Example: "yunxiao appstack variable-groups list --app my-app"},
	{ID: "appstack.variable_groups.create", Domain: "appstack", Description: "Create variable group",
		HTTPMethod: "POST", Path: ".../apps/{app}/variableGroup", Risk: risk.HighRiskWrite,
		Example: "yunxiao appstack variable-groups create --app a --from-revision-sha <sha> --name g --dry-run"},
	{ID: "organization.departments.list", Domain: "organization", Description: "List departments",
		HTTPMethod: "GET", Path: ".../platform/.../departments", Risk: risk.Read,
		Example: "yunxiao organization departments list"},
	{ID: "organization.roles.list", Domain: "organization", Description: "List roles",
		HTTPMethod: "GET", Path: ".../platform/.../roles", Risk: risk.Read,
		Example: "yunxiao organization roles list"},
	{ID: "project.get", Domain: "project", Description: "Get project by id",
		HTTPMethod: "GET", Path: ".../projects/{id}", Risk: risk.Read,
		Example: "yunxiao project get --id <id>"},
	{ID: "sprint.list", Domain: "project", Description: "List sprints",
		HTTPMethod: "GET", Path: ".../projects/{space}/sprints", Risk: risk.Read,
		Example: "yunxiao sprint list --space-id <id>"},
	{ID: "sprint.create", Domain: "project", Description: "Create sprint",
		HTTPMethod: "POST", Path: ".../projects/{space}/sprints", Risk: risk.Write,
		Example: "yunxiao sprint create --space-id <id> --name s1 --owners u1 --dry-run"},
	{ID: "versions.list", Domain: "project", Description: "List project versions",
		HTTPMethod: "GET", Path: ".../projects/{space}/versions", Risk: risk.Read,
		Example: "yunxiao versions list --space-id <id>"},
	{ID: "versions.delete", Domain: "project", Description: "Delete project version",
		HTTPMethod: "DELETE", Path: ".../projects/{space}/versions/{id}", Risk: risk.HighRiskWrite,
		Example: "yunxiao versions delete --space-id <sid> --id <vid> --dry-run"},
	{ID: "workitem.fields", Domain: "project", Description: "Work item type field config",
		HTTPMethod: "GET", Path: ".../workitemTypes/{type}/fields", Risk: risk.Read,
		Example: "yunxiao workitem fields --space-id <s> --type-id <t>"},
	{ID: "workitem.explore_workflow", Domain: "project", Description: "Probe workitem type status transition graph (multi-step)",
		HTTPMethod: "PUT", Path: ".../workitems/{id} (status probes) + GET .../workflows", Risk: risk.Write,
		Example: "yunxiao workitem +explore-workflow --type-id <t> --cleanup --dry-run"},
	{ID: "pipeline.service_connections.list", Domain: "pipeline", Description: "List service connections",
		HTTPMethod: "GET", Path: ".../serviceConnections", Risk: risk.Read,
		Example: "yunxiao pipeline service-connections list --type codeup"},
	{ID: "pipeline.host_groups.list", Domain: "pipeline", Description: "List host groups",
		HTTPMethod: "GET", Path: ".../hostGroups", Risk: risk.Read,
		Example: "yunxiao pipeline host-groups list"},
	{ID: "pipeline.flow_variable_groups.list", Domain: "pipeline", Description: "List Flow variable groups",
		HTTPMethod: "GET", Path: ".../flow/.../variableGroups", Risk: risk.Read,
		Example: "yunxiao pipeline flow-variable-groups list"},
	{ID: "codeup.repos.get", Domain: "codeup", Description: "Get repository",
		HTTPMethod: "GET", Path: ".../repositories/{id}", Risk: risk.Read,
		Example: "yunxiao codeup repos get --repo <id>"},
	{ID: "codeup.branches.create", Domain: "codeup", Description: "Create branch",
		HTTPMethod: "POST", Path: ".../branches?branch=&ref=", Risk: risk.HighRiskWrite,
		Example: "yunxiao codeup branches create --repo <id> --branch feat --ref master --dry-run"},
	{ID: "codeup.branches.delete", Domain: "codeup", Description: "Delete branch",
		HTTPMethod: "DELETE", Path: ".../branches/{branch}", Risk: risk.HighRiskWrite,
		Example: "yunxiao codeup branches delete --repo <id> --branch feat --dry-run"},
	{ID: "appstack.apps.create", Domain: "appstack", Description: "Create application",
		HTTPMethod: "POST", Path: ".../apps", Risk: risk.HighRiskWrite,
		Example: "yunxiao appstack apps create --name demo --dry-run"},
	{ID: "appstack.change_requests.list", Domain: "appstack", Description: "List app change requests",
		HTTPMethod: "POST", Path: ".../changeRequests:search", Risk: risk.Read,
		Example: "yunxiao appstack change-requests list --app my-app"},
	{ID: "appstack.global_vars.list", Domain: "appstack", Description: "List global vars",
		HTTPMethod: "POST", Path: ".../globalVars:search", Risk: risk.Read,
		Example: "yunxiao appstack global-vars list"},
	{ID: "testhub.cases.search", Domain: "testhub", Description: "Search testcases",
		HTTPMethod: "POST", Path: ".../testcases:search", Risk: risk.Read,
		Example: "yunxiao testhub cases search --repo-id <id>"},
	{ID: "testhub.directories.create", Domain: "testhub", Description: "Create testcase directory",
		HTTPMethod: "POST", Path: ".../directories", Risk: risk.Write,
		Example: "yunxiao testhub directories create --repo-id <id> --name dir --dry-run"},
	{ID: "appstack.release_workflows.list", Domain: "appstack", Description: "List app release workflows",
		HTTPMethod: "GET", Path: ".../apps/{app}/releaseWorkflows", Risk: risk.Read,
		Example: "yunxiao appstack release-workflows list --app my-app"},
	{ID: "appstack.release_workflows.stage.execute", Domain: "appstack", Description: "Execute release stage",
		HTTPMethod: "POST", Path: ".../releaseStages/{stage}/...execute", Risk: risk.HighRiskWrite,
		Example: "yunxiao appstack release-workflows stage execute --app a --workflow-sn w --stage-sn s --dry-run"},
	{ID: "appstack.deploy.machine_log", Domain: "appstack", Description: "Get machine deploy log",
		HTTPMethod: "GET", Path: ".../host/deployLog", Risk: risk.Read,
		Example: "yunxiao appstack deploy machine-log --tunnel-id 1 --machine-sn sn"},
	{ID: "appstack.deploy.add_hosts", Domain: "appstack", Description: "Add hosts to host group",
		HTTPMethod: "PUT", Path: ".../pools/instances/{i}/addHostList", Risk: risk.HighRiskWrite,
		Example: "yunxiao appstack deploy add-hosts --instance n --host-sns a,b --dry-run"},
	{ID: "pipeline.vm_deploy.get", Domain: "pipeline", Description: "Get VM deploy order",
		HTTPMethod: "GET", Path: ".../pipelines/{id}/deploy/{deployId}", Risk: risk.Read,
		Example: "yunxiao pipeline vm-deploy get --pipeline-id p --deploy-id d"},
	{ID: "pipeline.vm_deploy.stop", Domain: "pipeline", Description: "Stop VM deploy order",
		HTTPMethod: "PUT", Path: ".../deploy/{id}/stop", Risk: risk.HighRiskWrite,
		Example: "yunxiao pipeline vm-deploy stop --pipeline-id p --deploy-id d --dry-run"},
	{ID: "pipeline.resource_members.create", Domain: "pipeline", Description: "Add Flow resource member",
		HTTPMethod: "POST", Path: ".../resourceMembers/...?roleName=&userId=", Risk: risk.HighRiskWrite,
		Example: "yunxiao pipeline resource-members create --resource-type pipeline --resource-id id --role-name viewer --user-id u --dry-run"},
	{ID: "pipeline.resource_members.transfer_owner", Domain: "pipeline", Description: "Transfer Flow resource owner",
		HTTPMethod: "POST", Path: ".../transfer/owner?newOwnerId=", Risk: risk.HighRiskWrite,
		Example: "yunxiao pipeline resource-members transfer-owner --resource-type pipeline --resource-id id --new-owner-id u --dry-run"},
	{ID: "workitem.efforts.list", Domain: "project", Description: "List work item effort records",
		HTTPMethod: "GET", Path: ".../workitems/{id}/effortRecords", Risk: risk.Read,
		Example: "yunxiao workitem efforts list --id <id>"},
	{ID: "workitem.efforts.create", Domain: "project", Description: "Create actual effort record",
		HTTPMethod: "POST", Path: ".../workitems/{id}/effortRecords", Risk: risk.Write,
		Example: "yunxiao workitem efforts create --id <id> --actual-time 2 --gmt-start d --gmt-end d --dry-run"},
	{ID: "workitem.estimated_efforts.list", Domain: "project", Description: "List estimated efforts",
		HTTPMethod: "GET", Path: ".../workitems/{id}/estimatedEfforts", Risk: risk.Read,
		Example: "yunxiao workitem estimated-efforts list --id <id>"},
	{ID: "programs.search", Domain: "project", Description: "Search programs (project sets)",
		HTTPMethod: "POST", Path: ".../programs:search", Risk: risk.Read,
		Example: "yunxiao programs search --name demo"},
	{ID: "codeup.repos.create", Domain: "codeup", Description: "Create Codeup repository",
		HTTPMethod: "POST", Path: ".../repositories?createParentPath=true", Risk: risk.HighRiskWrite,
		Example: "yunxiao codeup repos create --name r --path r --dry-run"},
	{ID: "workitem.transition", Domain: "project", Description: "Multi-step workitem status transition (any type via profile.workflows)",
		HTTPMethod: "PUT", Path: ".../workitems/{id} (status multi-step)", Risk: risk.Write,
		Example: "yunxiao workitem +transition --id <id> --to <alias> --dry-run"},
	{ID: "codeup.tags.list", Domain: "codeup", Description: "List repository tags",
		HTTPMethod: "GET", Path: ".../repositories/{repo}/tags", Risk: risk.Read,
		Example: "yunxiao codeup tags list --repo <id>"},
	{ID: "codeup.tags.create", Domain: "codeup", Description: "Create repository tag",
		HTTPMethod: "POST", Path: ".../repositories/{repo}/tags?tagName=&ref=", Risk: risk.HighRiskWrite,
		Example: "yunxiao codeup tags create --repo <id> --tag-name v1 --ref master --dry-run"},
	{ID: "codeup.tags.delete", Domain: "codeup", Description: "Delete repository tag",
		HTTPMethod: "DELETE", Path: ".../repositories/{repo}/tags/{tagName}", Risk: risk.HighRiskWrite,
		Example: "yunxiao codeup tags delete --repo <id> --tag-name v1 --dry-run"},
	{ID: "codeup.protected_branches.list", Domain: "codeup", Description: "List protected branches",
		HTTPMethod: "GET", Path: ".../repositories/{repo}/protectedBranches", Risk: risk.Read,
		Example: "yunxiao codeup protected-branches list --repo <id>"},
	{ID: "codeup.protected_branches.get", Domain: "codeup", Description: "Get protected branch rule",
		HTTPMethod: "GET", Path: ".../protectedBranches/{id}", Risk: risk.Read,
		Example: "yunxiao codeup protected-branches get --repo <id> --id 1"},
	{ID: "codeup.protected_branches.create", Domain: "codeup", Description: "Create protected branch rule",
		HTTPMethod: "POST", Path: ".../repositories/{repo}/protectedBranches", Risk: risk.HighRiskWrite,
		Example: "yunxiao codeup protected-branches create --repo <id> --branch master --dry-run"},
	{ID: "codeup.protected_branches.delete", Domain: "codeup", Description: "Delete protected branch rule",
		HTTPMethod: "DELETE", Path: ".../protectedBranches/{id}", Risk: risk.HighRiskWrite,
		Example: "yunxiao codeup protected-branches delete --repo <id> --id 1 --dry-run"},
	{ID: "update", Domain: "cli", Description: "Self-update yunxiao binary from GitHub Releases (alias: self-update)",
		HTTPMethod: "N/A", Path: "local binary replace", Risk: risk.Write,
		Params: []Param{
			{Name: "check", Type: "bool", Required: false, Desc: "report only; exit 2 if update available (no download)"},
			{Name: "yes", Type: "bool", Required: false, Desc: "apply without prompt (scripts/CI; never silent)"},
		},
		Example: "yunxiao update --check"},
	{ID: "api.raw", Domain: "api", Description: "Raw HTTP escape hatch",
		HTTPMethod: "ANY", Path: "<path>", Risk: risk.Write, Example: "yunxiao api GET /oapi/v1/platform/user"},
}

// schemaAliases maps common / MCP-like ids onto Registry entries.
var schemaAliases = map[string]string{
	"project.searchWorkitems": "workitem.search",
	"search_workitems":        "workitem.search",
	"searchWorkitems":         "workitem.search",
	"self-update":             "update",
}

func Find(id string) *Method {
	if alt, ok := schemaAliases[id]; ok {
		id = alt
	}
	for i := range Registry {
		if Registry[i].ID == id {
			return &Registry[i]
		}
	}
	return nil
}

func List(domain string) []Method {
	if domain == "" {
		return append([]Method(nil), Registry...)
	}
	var out []Method
	for _, m := range Registry {
		if m.Domain == domain {
			out = append(out, m)
		}
	}
	return out
}
